---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1496746/public_html/jantungdesa
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH